CREATE TABLE [bkp].[job_obj_details] (
    [job_object_id]                 INT            IDENTITY (1, 1) NOT NULL,
    [job_id]                        INT            NOT NULL,
    [source_id]                     INT            NOT NULL,
    [source_job_id]                 INT            NULL,
    [object_id]                     INT            NULL,
    [source_container_name]         VARCHAR (1000) NULL,
    [source_object_path]            VARCHAR (1000) NULL,
    [source_object_name]            VARCHAR (255)  NULL,
    [source_query]                  VARCHAR (MAX)  NULL,
    [source_filter]                 VARCHAR (MAX)  NULL,
    [source_sheet_name]             VARCHAR (255)  NULL,
    [source_object_functional_name] VARCHAR (255)  NULL,
    [source_format]                 VARCHAR (255)  NULL,
    [source_object_delimiter]       VARCHAR (255)  NULL,
    [source_partitioned_by]         VARCHAR (255)  NULL,
    [source_update_identifier]      VARCHAR (255)  NULL,
    [source_update_identifier_hist] VARCHAR (255)  NULL,
    [source_delete_identifier]      VARCHAR (255)  NULL,
    [target_container_name]         VARCHAR (1000) NULL,
    [target_object_path]            VARCHAR (1000) NULL,
    [target_object_name]            VARCHAR (1000) NULL,
    [target_table_type]             VARCHAR (255)  NULL,
    [target_format]                 VARCHAR (255)  NULL,
    [target_object_delimiter]       VARCHAR (255)  NULL,
    [target_partitioned_by]         VARCHAR (255)  NULL,
    [enabled]                       INT            NULL,
    [load_type]                     VARCHAR (255)  NULL,
    [rejected_object_path]          VARCHAR (255)  NULL,
    [common_log_object_path]        VARCHAR (255)  NULL,
    [common_log_object_name]        VARCHAR (255)  NULL,
    [last_modified_date]            DATETIME       NULL,
    [is_absolute_path]              INT            NULL,
    [method_name]                   VARCHAR (500)  NULL,
    [dq_check_flag]                 INT            NULL,
    [is_full_load]                  INT            NULL,
    [is_full_load_hist]             INT            NULL,
    [last_run_time]                 DATETIME       NULL,
    [Source_column_mapping]         VARCHAR (255)  NULL,
    [dependent_table_list]          VARCHAR (8000) NULL,
    [execution_sequence]            INT            NULL
);

