CREATE TABLE [bkp].[object_column_mapping_11082023] (
    [col_mapping_key]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [job_object_id]                  INT            NOT NULL,
    [object_id]                      INT            NOT NULL,
    [source_column_name]             VARCHAR (255)  NULL,
    [column_type]                    VARCHAR (100)  NULL,
    [target_column_name]             VARCHAR (255)  NULL,
    [target_column_data_type]        VARCHAR (255)  NULL,
    [is_nullable]                    VARCHAR (255)  NULL,
    [transformation_rule]            VARCHAR (4000) NULL,
    [actv_flg]                       VARCHAR (1)    NOT NULL,
    [source_format]                  VARCHAR (255)  NULL,
    [target_format]                  VARCHAR (255)  NULL,
    [length]                         INT            NULL,
    [source_column_flag]             INT            NULL,
    [surrogate_key_flag]             INT            NULL,
    [alphanumeric_key_flag]          INT            NULL,
    [uniqueness_key_flag]            INT            NULL,
    [natural_key_flag]               INT            NULL,
    [house_keeping_column_flag]      INT            NULL,
    [derived_column_flag]            INT            NULL,
    [foreign_key_flag]               INT            NULL,
    [column_included_in_SCD]         INT            NULL,
    [length_key_flag]                INT            NULL,
    [range_key_flag]                 INT            NULL,
    [range_expression]               VARCHAR (255)  NULL,
    [type_check_flag]                INT            NULL,
    [column_id]                      INT            NULL,
    [null_check_nk_combination_flag] INT            NULL
);

